# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Xeliger
email: dcristianeduardo4@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
domain: cristianeddu-byte.github.io
url: https://cristianeddu-byte.github.io 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: vvalchev/creative-theme-jekyll-new
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

